defaults:
  - override hydra/launcher: submitit_local

# environment
task: dog-run
obs: rgb
obs_size: 64
time_limit: 125
num_frames: 3
env_config_path: ???

# evaluation
checkpoint: ???
checkpoint_buffer: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
device: cuda
buffer_size: 1_000_000
buffer_storage_device: ???
use_variable_sequence_length: False
exp_name: default
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: ???
wandb_entity: ???
wandb_group_name: ???
wandb_run_name: ???
wandb_run_id: ???
wandb_silent: false
disable_wandb: true
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1
save_every: 10000
save_checkpoint_wandb: false

# slot extractor wrapper
pre_initialize_slots: false

# slot extractor
slot_extractor_model: akornsaur
n_slots: 5
slot_dim: 64
slot_extractor_checkpoint_path: ???
slot_extractor_device: cuda
per_slot_initialization: true
deterministic_initialization: true

# dinosaur
dino_model_name: vit_base_patch16_224_dino
input_feature_dim: 768
num_patches: 196
features: [ 2048, 2048, 2048 ]

# akornsaur
L: 2
ch: 256
autorescale: true
psize: 8
T: 8
maxpool: true
heads: 8
gta: true
N: 4
gamma: 1
J: attn
use_omega: false
global_omg: false
c_norm: gn
learn_omg: false
use_ro_x: false
no_ro: false
project: true

# savi
savi_feature_dim: 64
savi_hidden_dim: 128
savi_num_iterations: 1
savi_num_initial_iterations: 3
savi_num_channels: [ 32, 32, 32, 32 ]
savi_kernel_size: 5

# slot-contrast
normalize_slots: false

# sold
sold_dynamics_num_context: 3
sold_dynamics_token_dim: 256
sold_dynamics_hidden_dim: 512
sold_dynamics_num_layers: 4
sold_dynamics_num_heads: 8
sold_dynamics_residual: True
sold_dynamics_teacher_forcing: False

sold_reward_token_dim: 256
sold_reward_num_heads: 8
sold_reward_num_layers: 4
sold_reward_hidden_dim: 512
sold_reward_num_mlp_layers: 1

sold_actor_token_dim: 256
sold_actor_num_heads: 8
sold_actor_num_layers: 4
sold_actor_hidden_dim: 512
sold_actor_num_mlp_layers: 1

sold_critic_token_dim: 256
sold_critic_num_heads: 8
sold_critic_num_layers: 4
sold_critic_hidden_dim: 512
sold_critic_num_mlp_layers: 1

sold_min_std: 0.1
sold_max_std: 1
sold_init_std: 2

# oc world model
use_interactions: true

# ddlp
world_model_type: ???
transition_model_type: ???
eit_masking: true
eit_embed_dim: 64
eit_h_dim: 256
eit_n_head: 8
eit_dropout: 0
eit_action_particle: true
eit_use_background: false
ddlp_config_path: ???
ddlp_checkpoint_path: ???

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
action_lower_bound: ???
action_upper_bound: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

# collect dataset
do_collect_episodes: false
n_train_episodes: ???
n_val_episodes: ???
dataset_path: ???
epsilon_greedy_start: 1.0
epsilon_greedy_end: 0.0
noise_scale_start: 2.8
noise_scale_end: 0.0
schedule_fraction: 1
